SELECT DISTINCT A.MEMBER_ID,
		B.CALENDAR_YEAR_MONTH,
        A.ACTIVITY_YEAR_MONTH,
		CASE 
			WHEN A.ACTIVITY_YEAR_MONTH = B.CALENDAR_YEAR_MONTH
				THEN 1
			ELSE 0
			END AS FLAG
	FROM REVENUE_ANALYSIS A
	INNER JOIN (
		SELECT DISTINCT CALENDAR_YEAR_MONTH
		FROM `CALENDAR`
		WHERE CALENDAR_YEAR_MONTH >= 201701
			AND CALENDAR_DAY_OF_MONTH <= 201806
		) B ON 1 = 1
	WHERE BANK_TYPE_ID = 0
		AND WAGER_AMOUNT > 1
        ORDER BY 1,2